use_frameworks!

target 'CountdownView_Example' do
  pod 'CountdownView', :path => '../'

  target 'CountdownView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
